### ISSUE TITLE
daisyUI 3.0.3 rompe el componente sidebar

### ISSUE THREAD

**Issue by charlyautomatiza** [manuelernestog/astrofy#22]
Hola Manuel.
Ante todo muchas gracias, dado que utilizo tu template con algunas cosas custom que le agregué a mi site personal: https://charlyautomatiza.vercel.app/

Al intentar usar la versión más reciente de este momento de **daisyUI 3.0.3**, no levanta el componente SideBar.astro, no se visualiza error pero directamente el componente no se renderiza.

Con la versión: "daisyui": "2.51.6" esto no ocurre.

**Comment by manuelernestog** [comment]
Hola Charly que tal. Gracias por el feedback, me alegro de que te sea de provecho la plantilla. 

La verdad ni sabía que Daisy se había actualizado. Tan pronto tenga un tiempo actualizo las dependencias y veo qué problema tiene. Saludos.

**Comment by manuelernestog** [comment]
Hecho! El ya quedo actualizada la versión a DaisyUI 3 y solucionados los problemas con el sidebar en la v2.5.0 !
