### ISSUE TITLE
Demo link correction (README.md)

### ISSUE THREAD

**Issue by GrungeElFz** [manuelernestog/astrofy#25]
File: `README.md`

In `Demo` section
↳ Replace [Astrofy](https://astrofy.astrofy-template.app/) --> (https://astrofy.astrofy-template.app/)
↳ By [Astrofy](https://astrofy-template.netlify.app/) --> (https://astrofy-template.netlify.app/)

**Comment by manuelernestog** [comment]
Thanks  @GrungeElFz, nice catch  :+1:  Obviously copy and paste in the wrong place haha
