### ISSUE TITLE
Website only shows checkbox

### ISSUE THREAD

**Issue by R3iyn** [manuelernestog/astrofy#26]
When cloning the repo, running npm install and npm run dev with the latest version (2.5.0), the website is not loading correctly for me.
I can see all of the generated HTML and CSS in the developer console, but none of it is visible in the browser itself.
When doing the same steps on 2.3.0, it still works.

**Comment by manuelernestog** [comment]
@R3iyn  Are you using node v18 ?

Did you already try removing node_modules folder and runing npm install again ?

**Comment by R3iyn** [comment]
Yes, it seems to be related to Windows 10. I've tried in on my Mac and a Windows 11 laptop today, and it seems to work there.

**Comment by manuelernestog** [comment]
I think then maybe is something wrong in your computer with windows 10. Maybe something with node version because I can't figure out something else. I'm closing this Issue for now, if I have any other report about this I'll try to dig in
