### ISSUE TITLE
Code snippets in .md files

### ISSUE THREAD

**Issue by 2618094** [manuelernestog/astrofy#29]
Hola!

I stuck in issue - when .md files contains code snippets like this 
```bash
max@DESKTOP:~/DEV/test$ docker-compose exec php vendor/phpunit/phpunit/phpunit --testsuite Feature
```
it render with fixed width and in mobile devices view horizontal scroll appears.

Reproduce: add snippet above to blog post and check on mobile device.

I'm really poor with css and cannot solve this problem :(

**Comment by manuelernestog** [comment]
Hey man I just tested this and looks good.
![image](https://github.com/manuelernestog/astrofy/assets/53962116/ab3f4de8-1324-4e5d-96f1-71285c5c4593)

This is my .md example code

![image](https://github.com/manuelernestog/astrofy/assets/53962116/7e2fbf04-08be-46f5-a163-711517a5672b)

**Comment by 2618094** [comment]
This is strange - i clone fresh repo and add this snippet

<img width="972" alt="image" src="https://github.com/manuelernestog/astrofy/assets/9998200/399a5b72-49f4-425c-9f05-7bdfe1548812">

<img width="660" alt="image" src="https://github.com/manuelernestog/astrofy/assets/9998200/ba10d222-b5d6-4164-b374-3ee23c0408c4">

**Comment by manuelernestog** [comment]
Hmmmm maybe this is some kind of incompatibility with Safari. Let me see if I find a way to run this on Linux.

Also, if you can install any other browser and try to replicate it, it will give me clue about if this is just an error on Safari.

**Comment by 2618094** [comment]
Checked in Chrome (Version 114.0.5735.198 (Official Build) (x86_64)), same.
Checked twice:
- fresh clone
- no changes except this snippet
- `npm run dev`
- http://localhost:3000/blog/post3

And i see on your screen - you make it one line - ``` should be higher and lower the code for snippet render

<img width="1104" alt="image" src="https://github.com/manuelernestog/astrofy/assets/9998200/e7e0798d-b427-4b2f-b546-b237a56f0fe2">
 
<img width="1020" alt="image" src="https://github.com/manuelernestog/astrofy/assets/9998200/65848a60-f67e-4e8b-ad77-562cd17b9989">

**Comment by manuelernestog** [comment]
Thanks for the feedback @2618094 I'll take a look 👍️

**Comment by manuelernestog** [comment]
@2618094 I already solved it, please try again and please let me know if it's ok to close the issue

**Comment by 2618094** [comment]
@manuelernestog working! CSS is just magic :)
¡Muchas gracias!
