### ISSUE TITLE
Blog tags?

### ISSUE THREAD

**Issue by dandv** [manuelernestog/astrofy#31]
Thanks for the slick theme!

Any chance to add blog tags? (Liked that feature in [this theme](https://github.com/hellotham/hello-astro/issues/19) but it has some navigation issues.)

**Comment by manuelernestog** [comment]
Hi @dandv glad you like the theme. Yes, I think this could be usefully. Thanks for the sugest.

**Comment by manuelernestog** [comment]
Work in progress on #38.

**Comment by manuelernestog** [comment]
Done in #38
