### ISSUE TITLE
Themes not available

### ISSUE THREAD

**Issue by Nabeel-javaid** [manuelernestog/astrofy#32]
Hey, can you pls tell me why is it not showing me the option to change the theme?

**Comment by manuelernestog** [comment]
Hey @Nabeel-javaid the theme option is just available in the deployed website to show the different themes, normally in a website we leave a theme according to the one we like the most and that is why it does not appear in the main branch.

If you want to have the option, you can download the deployed branch, and you will find it there.

**Comment by Nabeel-javaid** [comment]
> Hey @Nabeel-javaid the theme option is just available in the deployed website to show the different themes, normally in a website we leave a theme according to the one we like the most and that is why it does not appear in the main branch.
> 
> If you want to have the option, you can download the deployed branch, and you will find it there.

hey @manuelernestog what do you mean by "you can download the deployed branch, and you will find it there."

I will really appreciate if you can guide me more

**Comment by manuelernestog** [comment]
Hey @Nabeel-javaid . Here https://github.com/manuelernestog/astrofy/tree/demo

Clone that branch and take a look. You will find the Theme selector in the corner.

**Comment by Nabeel-javaid** [comment]
> Hey @Nabeel-javaid . Here https://github.com/manuelernestog/astrofy/tree/demo
> 
> Clone that branch and take a look. You will find the Theme selector in the corner.

Thanks! the issue has been resolved
