### ISSUE TITLE
Update to Astro 3.0

### ISSUE THREAD

**Issue by qvacode** [manuelernestog/astrofy#42]
Astro version 3.0 is here. Improvements are included in the following aspects:
- Image Optimization (stable): Unflagged and better than ever. 
- Faster Rendering Performance: Astro components render 30-75% faster. 
- SSR Enhancements for Serverless: New ways to connect to your hosting platform.
- HMR Enhancements for JSX: Fast Refresh support for React and Preact. 
- Optimized Build Output: Cleaner and    more performant HTML. 

It would be interesting to migrate to this version. greetings

**Comment by brahimABD98** [comment]
@qvacode  #40 already submitted I hope @manuelernestog approve it soon :)
