### ISSUE TITLE
Blog improvments

### ISSUE THREAD

**Issue by coreyryanhanson** [manuelernestog/astrofy#44]
The blog collections in this template had a few behavior annoyances for my use case as I was migrating my blog posts.

1. In the markdown for blog posts, the default behavior redirected people away from the site instead of opening a new tab. Specifying each time for each markdown file is cumbersome.
2. The behavior for blog paths was extremely rigid.
    - There was no way of auto-generating slugs from the blog title (to have better inclusion of keywords in the url than the default behavior).
    - The links would break if blog posts were nested in self contained subfolders (for storing post assets) (Although if maintaining posts in simple markdown for multiple platforms, this wouldn't be an effective way of storing images without an additional modification)

I already made fixes while building my website. One is a hacky use of the base tag but a solution that is far from ideal, but the second may be beneficial as a PR (let me know if I should).

https://github.com/coreyryanhanson/astrofy/tree/dev-blog-slug-from-title

I think the template would benefit by solving both issues cleanly.

**Comment by manuelernestog** [comment]
Hi @coreyryanhanson. Thanks for the suggestions.

1. About this, I think we should leave this as it's. Sadly, markdown do not support the target _blank and if someone want to use it, it will need to create an <a> tag. We can change this in our template including a `<base target="_blank">` in the postLayout and this will redirect all the link to other tab but if the user use an internal link it will open a new tab. In conclusion, we don't have a clear way to make this, and I think this should be in the user hands. 

2. Uses the title for generating the slug it's a nice change.

If you want, you can go ahead with the PR! 🤝

**Comment by coreyryanhanson** [comment]
@manuelernestog Sounds good! I just brought the branch up to date with the repo and made a pull request. Looking forward to trying out the new tag system that's been implemented :)
