### ISSUE TITLE
moving images under src

### ISSUE THREAD

**Issue by brahimABD98** [manuelernestog/astrofy#45]
according to the [image docs](https://docs.astro.build/en/guides/images/#where-to-store-images) we should consider moving images under src/ since currently all images are in the public folder 
we should consider applying the AVIF format to all images

**Comment by manuelernestog** [comment]
Nice suggestion @brahimABD98!

I think we can leave the svg in public and move the other ones.
About the AVIF format. If we are going to use this should be using the picture tag adding support for old browsers. webp has less compression but better support at least for now.

**Comment by manuelernestog** [comment]
I'm going to decline this as we have blog posts that can get external resources is easy to give this possibility to the user.

**Comment by manuelernestog** [comment]
I'm going to decline this as we have blog posts that can get external resources is easy to give this possibility to the user.

**Comment by brahimABD98** [comment]
Yes, I agree @manuelernestog recently I had some trouble importing images from content folder when I tried to do this inside an md file.
```html
<img src="./images/image.png" width="300" alt="img" />
```
but importing from the public folder works just fine
```html
<img src="/image.png" width="300" alt="image" />
```

**Comment by manuelernestog** [comment]
Thanks for confirming @brahimABD98

 Regards 🙌
