### ISSUE TITLE
Remove `npm` and update `README`

### ISSUE THREAD

**Issue by HarshPatel5940** [manuelernestog/astrofy#51]
## Expected Behavior
  It should only have `pnpm` related files as we already shifted to it and its better.

## Current Behavior
  we still have `package-lock.json` and the README still contains `npm` commands.

# Description
   I am willing to make a PR for this issue and contribute to this project.

**Comment by mgerezqa** [comment]
Hello, I'm asking you, I'm using this template for a blog, and when deploying to github pages I get an error related to "Error: Error: No pnpm version is specified." Does the change you are suggesting have anything to do with it? Sorry, I just started using astro and I couldn't find how to solve this problem.
![image](https://github.com/manuelernestog/astrofy/assets/54424951/bcafe9dd-37d0-4672-9d67-a47dad4ff161)

**Comment by HarshPatel5940** [comment]
Not exactly, but it will get fixed with my changes!

**Comment by HarshPatel5940** [comment]
Let me know if you want a PR for this. I will create it ASAP.

**Comment by mgerezqa** [comment]
> Let me know if you want a PR for this. I will create it ASAP.

Hello! Yes it would be of great help!

**Comment by manuelernestog** [comment]
Hey @HarshPatel5940 thanks for letting us know about that, and sorry for the late response. I'll do it right now

**Comment by HarshPatel5940** [comment]
> Hey @HarshPatel5940 thanks for letting us know about that, and sorry for the late response. I'll do it right now

It's great that you replied! Looking forward more from you :D 
Happy Open Sourcing
