### ISSUE TITLE
Update to Astro 4, mdx 2, and DaisyUI 4

### ISSUE THREAD

**Issue by WingofaGriffin** [manuelernestog/astrofy#52]
Updating my site fork to these appears to have no real issues, but always nice to have upstream take a look too.

https://astro.build/blog/astro-4/

https://daisyui.com/docs/changelog/

https://github.com/withastro/astro/blob/main/packages/integrations/mdx/CHANGELOG.md

**Comment by manuelernestog** [comment]
I don't see any braking changes. Looks good 👌

**Comment by manuelernestog** [comment]
Done!
