### ISSUE TITLE
I'm sorry to ask a question, I hope someone can answer.

### ISSUE THREAD

**Issue by grey6966** [manuelernestog/astrofy#69]
Why is it that in the example, the path for "store" is "/store/item1" and can be accessed directly, while the path for "blog" is "/blog/demo-post-3"? Is there a configuration that determines this?

**Comment by grey6966** [comment]
I am a backend programmer and not very familiar with frontend. What I mean is, the store page can be accessed directly through the path of the md file, while accessing the blog is not through the file path. I hope someone can help me.

**Comment by RealSollyM** [comment]
In the `src/pages/blog/[...page].astro` file, line 35, there is a function call (`createSlug`) that takes in the blog title and the file name (slug) to create a new slug. The actual function is in the lib folder. You can choose to use the slug without the createSlug function itself.

**Comment by grey6966** [comment]
Thank you very much. I understood everything once I noticed this method.
`export default function (title: string, staticSlug: string) {
  return (
    !GENERATE_SLUG_FROM_TITLE ? staticSlug : title
      // remove leading & trailing whitespace
      .trim()
      // output lowercase
      .toLowerCase()
      // replace spaces
      .replace(/\s+/g, '-')
      // remove special characters
      .replace(/[^\w-]/g, '')
      // remove leading & trailing separtors
      .replace(/^-+|-+$/g, '')
  )
}`

**Comment by grey6966** [comment]
> In the `src/pages/blog/[...page].astro` file, line 35, there is a function call (`createSlug`) that takes in the blog title and the file name (slug) to create a new slug. The actual function is in the lib folder. You can choose to use the slug without the createSlug function itself.

Thank you very much. I understood everything once I noticed this method.
 function (title: string, staticSlug: string) {
  return (
    !GENERATE_SLUG_FROM_TITLE ? staticSlug : title
      // remove leading & trailing whitespace
      .trim()
      // output lowercase
      .toLowerCase()
      // replace spaces
      .replace(/\s+/g, '-')
      // remove special characters
      .replace(/[^\w-]/g, '')
      // remove leading & trailing separtors
      .replace(/^-+|-+$/g, '')
  )
}
