### ISSUE TITLE
DaisyUI theme change 

### ISSUE THREAD

**Issue by muke78** [manuelernestog/astrofy#73]
I'm making my portfolio too, but I'm looking for the dropdown of the themes you included but I don't know how to put it in or if it's a paid option

![Captura de pantalla 2024-10-04 193430](https://github.com/user-attachments/assets/24978ff1-2b51-4149-8e22-309c1741c9fe)

**Comment by aaronlippold** [comment]
I ran into the same issue, what was your fix?

**Comment by muke78** [comment]
Practically it was from the daisyUI theme controller, which is provided by default, I merged it with the one that comes from the official page, the themes were arranged in an arrangement and I went through them with their main colors, bg-primary, bg-secondary, bg- accent, bg-neutral, if you want the solution it is in my GitHub repository called Portfolio ✨
